### PR TITLE
added Gruntfile, validated Javascript in jshint, added distribution version

### PR DESCRIPTION
**Pull request by stefanocudini**

### CODE REVIEW

**Comment by aparshin** [comment]
Thanks a lot for the PR!

Unfortunately, I see several issues with Grunt file:
- there is an error in `cssmin` task: no file with name `src/<%= pkg.name %>.css`
- It is not very good idea to store `dist` folder (and any other generated files) in the repository. I hope most users are able to run `npm i` and `grunt` to build production files themselves. Could you, please, delete these files and add `dist` folder to `gitignore`.
- Why do you turn off jshint warnings `W099`, `W044` in gruntfile? `W033` and `W083` can be removed after I fix corresponding places in sources (will do it today).
- We use spaces for indentation. Could you, please, replace tabs in `Gruntfile.js`.

**Comment by aparshin** [comment]
I missed another problem with building: images should be copied to `dist` folder along with css files...

**Comment by stefanocudini** [comment]
yoou can use this Grunt plugin: https://github.com/gruntjs/grunt-contrib-copy

**Comment by zverev** [comment]
Sorry for the late answer.

We use gulp, so I've added a linter as gulp plugin.
As for minification, I don't think this to be our case. Plugin size is only 10k.

**Pull request closed without merging**
